print("Ciao strimpellatore squattrinato")
print("Io sono Rockivander...")
print("Il più famoso generatori di nomi per cantanti rock")
print("Dove hai detto che sei nato?")
luogo_nascita=input()
print("Conoscevo una strumentessa molto carina di " + str (luogo_nascita) + "... quanti ricordi...")
print("E di quale specie è il tuo animale domestico?")
animale_domestico=input()
print("Il nome di voi quattro scappati di casa sarà...")
print("sarà...")
print("Il " + str (animale_domestico) + " di " + str (luogo_nascita))
print("E ricorda, è il nome che sceglie il cantante signor " + str (animale_domestico) + " di " + str (luogo_nascita))